mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis
  ports:
    - "6379:6379"

rabbitmq:
  image: rabbitmq:3.6.1-management
  ports:
    - "15672:15672"
    - "5672:5672"

dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
